---
title: Phylogenetic adaptions to urban living in Australian birds
author: "Corey T. Callaghan, John Wilshire, XXXX, XXXX, Richard T. Kingsford, William K. Cornwell"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  bookdown::tufte_html2:
    number_sections: no
    toc: no
  bookdown::word_document2: null
bibliography: references.bib
fontsize: 12pt
link-citations: no
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/global-ecology-and-biogeography.csl
---

# ABSTRACT


https://www.youtube.com/watch?v=9Gc4QTqslN4



# INTRODUCTION
Urbanization fragments and isolates natural habitat [@marzluff2001restoration; @melles2003urban; @loram2007urban], thus globally threatening biodiversity [@mckinney2006urbanization; @mckinney2008effects]. Despite the documented loss of biodiversity directly or indirectly caused by urbanization [@mckinney1999biotic; @mckinney2006urbanization], some species have successfully adapted to, colonized and subsequently thrived in urban environments [@mckinney2002urbanization; @chace2006urban; @lowry2013behavioural; @mcdonnell2015adaptation].

Within urban ecosystems there are generally urban avoiders, urban adapters, and urban exploiters [@mckinney2002urbanization; @mckinney2006urbanization; @kark2007living; @mcdonnell2015adaptation]. Urban avoiders are sensitive to urban environments [@mcdonnell2015adaptation] and tend to apportion more energy towards reproduction, relative to adapters and exploiters [@croci2008does]. Urban adapters can utilize urban environmental resources but may not reside in them [@mcdonnell2015adaptation] and are generally sedentary, social, high fecundity, with wide distribution [@kark2007living, @croci2008does]. Urban exploiters thrive in urban environments [@mcdonnell2015adaptation] and are generally more social and sedentary than adapters [@kark2007living]. Species’ traits such as social status, behavioral flexibility, migratory status, nesting, diet preferences, habitat preferences, and overall species range have all been used to predict presence in urban environments [@mcclure1989characterizes; @mills1989effects; @jokimaki1998distribution; @lim2004responses; @clergeau2006avifauna; @chace2006urban; @lowry2013behavioural]. Understanding which favored traits are associated with urban adapters and avoiders [@croci2008does] and their habitats can inform management decisions for conservation of particular species and improvements of habitats within urban environments.

Rather than a specific trait that predicts a species’ ability to be an urban avoider, adapter or exploiter, it is more likely a combination of traits. For instance, urban adapters’ presence in Jerusalem was predicted by a combination of traits including diet, degree of sociality, sedentariness, and preferred nesting sites [@kark2007living]. While a regional analysis throughout France and Switzerland demonstrated urban adapters prefer forested habitats, are sedentary, omnivorous, high-nesters, and were widely distributed [@croci2008does].

Despite the number of studies which have investigated the relationships between species' traits and urban adaptedness, most studies are either spatially limited, such as a single city or region [@blair1996land; @kark2007living; @croci2008does]; or temporally limited to a single breeding season [@blair1996land] or two month survey period [@kark2007living]]. Moreover, the terminology (i.e., urban adapters, avoiders, and exploiters) is used differently among studies [cf., [@kark2007living] and [@croci2008does]], potentially affecting interpretation between scientists and the public [@mcdonnell2015adaptation; @fischer2015categorizing].

Fortunately, citizen science [see reviews by @devictor2010beyond; @tulloch2013realising; @bonney2014next; @kobori2016citizen] can provide broad-scale empirical datasets, allowing us to test hypotheses at spatial and temporal scales previously difficult to attain. This data provides a cost-effective method to research the relationship between species' traits and urban observations. Various projects have used citizen science data to elucidate information on abundance and distribution of birds in urban ecosystems [@mccaffrey2005using; @callaghan2017assessing], as well as functional composition of urban birds [@la2014role; @morelli2016evidence; @lepczyk2017global].

Here, we use data from eBird [@sullivan2009ebird; -@sullivan2014ebird], a successful citizen science project with over 500 million observations, submitted by more than 250,000 participants [@sullivan2017using], in order to elucidate adaptations in Australian birds to urban living. We combine eBird data with multiple input rasters, that represent a continuous levels of urbanness, over the whole of Australia. This is opposed to assigning species to a priori groups (adapters, avoiders, or exploiters) and investigating differences in traits among groups [e.g., @kark2007living]. We then apply phylogenetically controlled models in order to assess species traits that predict pre-adaptation to urban living. We hypothesize that a combination of traits allows species to thrive in urban environments.







# METHODS
## Study area
We looked at bird observations throughout the whole of continental Australia. Bird observations from outlying islands were eliminated from potential analysis.

## Bird observation data
Bird observations originated from eBird [@sullivan2009ebird; @sullivan2014ebird], a large-scale empirical dataset collected by citizen scientists. Volunteer birdwatchers submit lists of species seen or heard at a given location, over a user-determined duration and survey area [@wood2011ebird]. We downloaded the eBird basic dataset (version ebd_relFeb-2018), and used all observations between January 1, 2010 - February 28, 2018. This temporal scale was used because eBird data are richest. This time frame was also used to minimize undue leverage of mismatch between changes in the response variable measurement (see response variable below) over the given time frame.

We filtered the bird observations (sensu [@callaghan2017assessing; @larole2014role]) by only including observations which were on complete checklists and which followed these protocols: travelling, random, stationary, area, or BirdLife Australia protocols [@barret2003new]. Further, we filtered the checklists to those with a distance travelled of < 5 km or an area covered which was < 500 Ha. Any checklists which were shared among multiple individuals were subsampled to include only one checklist in order to avoid duplicate results.

Seabirds (gannets, petrels, shearwaters, etc.) were omitted from the analyses as we do not expect any correlation with seabirds using urban areas under normal circumstances. Only species which included > 100 observations in the eBird database over the specified time-frame, and that met our criteria were considered for further analyses.

## Response variable - an urbanization index
We used VIIRS night-time lights [@eldvidge2017viirs] as a proxy of a bird's association with urban habitat. The VIIRS night-time lights measures the electric lighting present on Earth's surface which is generally associated with human settlement. There are also a significant number of steps (e.g., filtering out background noise, degraded data, and other light source contamination) which are used to ensure the validity of the data and its association with human settlement [@eldvidge2017virrs]. For all checklists which met our criteria above (N=length(unique(urbanness$SAMPLING_EVENT_IDENTIFIER))), we used the associated spatial coordinates and Google Earth Engine [@gorelick2017google] to assign the average radiance value calculated from the VIIRS layer. For each location, we calculated the average radiance within a 5 km buffer, in order to match the spatial scale of the checklists included and to minimize any potential bias.

Each checklist's average radiance value was then passed to every bird on that checklist, which provided every species with a distribution of average radiance values (Fig. 1). For all species, we then used the median of this distribution as a continuous urbanization index.

## Explanatory variables
Explanatory variables were calculated using a published dataset which contains the biological, ecological, and conservation information for all of Australia's birds [@garnett2015biological]. Potential traits were chosen on the basis of their existing support and hypotheses in the current literature (e.g., [@mcclure1989characterizes; @kark2007living; @evans2011makes]). Traits were parsed in different manners, and for any missing value in the dataset, we treated that as evidence against it existing (i.e., if a species had NA for a specific habitat, we assumed that the lack of evidence found by the authors indicates that the species is unlikely to be found in that habitat). Supplementary table 1 provides an overview of all candidate traits, associated references for each trait, and more detailed information on how the traits were calculated.

Only species which had complete data for the list of candidate traits were considered in the analyses.

## Phylogenetic analysis
For the phylogenetic portion of our analyses, we used the phylogenetic tree provided by Jetz et al. [@jetz2012global]. This phylogeny represents the first completely mapped phylogeny of 9,993 birds [@jetz2012global].

In order to assess whether there was a phylogenetic signal of the urbanization index used in our study, we used the phylosignal package [@keck2016phylosignal] in the R computing environment [@r2017coreteam].

### Taxonomic considerations
Given the diverse datasets used in this analysis, there were differing taxonomic authorities followed. The response data from eBird follows the eBird/clements checklist [http://www.birds.cornell.edu/clementschecklist/], while the biological and ecological data follows the working list of Australian birds by BirdLife Australia [http://www.birdlife.org.au/conservation/science/taxonomy], and the phylogenetic tree followed the BirdLife V3 world checklist [http://birdtree.org/taxonomy/]. There were minor differences which existed in recognized species among the three datasets. A taxonomic key was made which combined the three different taxonomies (Supplementary Table 2). Ultimately, a species' response variable, calculated from the eBird database and taxonomic source, was considered for analysis if it matched for both the trait dataset and the phylogenetic tree dataset. If it did not match both, then it was not considered for analysis (e.g., species currently only recognized by eBird/clements such as Western Whistler, Silver-backed Butcherbird, or Paperbark Flycatcher). Additionally, one species (Aleutian Tern) met the criteria for number of observations above, but was not included in the Australian trait data because it is new to Australia.

## Models


# RESULTS
A total of ```nrow(all_eBird_data)``` observations were used in the analysis.

# DISCUSSION

# REFERENCES
