---
title: "non_phylo_analyses"
author: "Everyone"
date: "3/22/2018"
output: pdf_document
---


matching

```{r}
response_variables$binom<-response_variables$SCIENTIFIC_NAME_tree
df<-left_join(traits,response_variables, by="binom") %>%
  filter(SCIENTIFIC_NAME_tree != "not_treated_as_species") %>%
  # drop columns that we aren't inerested in
  dplyr::select(-brain_size)
```


look at the continuous ones
```{r}
library(corrplot)
select_if(df, is.numeric) %>%
  cor(use="pairwise.complete.obs") %>%
  corrplot
```


completely naive model, plant eater taken out cause it only had one level.

Logging response cause it is right-skewed and produced crazy residual plots.

```{r}
names(df)
df %>%
filter_all(all_vars(!is.na(.)))->df2

naive_mod<-lm(log(urban_median)~log(mean_body_size)+log(clutch_size)+iucn_status+feeding_habitat_generalism+agricultural+grass_shrubland+tree_forest+breeding_habitat_generalism+granivore+insectivore+carrion_eater+diet_generalism+plant_eater+movement_class+ground_nesting+hollow_nesting+nest_generalism+breeding+nest_aggregation+feeding_aggregation,data=df2,na.action = "na.fail", weights=(df2$N/df2$unique_localities))
summary(naive_mod)
dim(df2)
```

```{r}
plot(naive_mod)

```



looking at the model in more depth

```{r}
anova(naive_mod)
```
and some not-so-quick model selection.  dredge takes a little while because it considers all combinations of predictor variables.

```{r}
#library(MuMIn)
#dredge(naive_mod,trace = TRUE)
modselect<-step(naive_mod)
```

```{r}
library(visreg)
visreg(modselect)
```